### ISSUE TITLE
Continuous logging error caused by F to C conversion

### ISSUE THREAD

**Issue by keness521** [Elethom/homebridge-gree-heatercooler-v2#9]
I think I might have bumped into an issue with the conversion of Fahrenheit to Celsius when at the upper limits of the range. (Quite possibly also at the lower end as well?)

My unit has a minimum of 16 and maximum of 30, in Celsius, and I've set those values in my config.

...
    "minimumTargetTemperature": 16,
    "maximumTargetTemperature": 30,
...

But I use Fahrenheit in HomeKit. No problems so far, it displays 64 to 86 in the Home, the same as the Gree wireless remote.

However, when I set to 86 degrees, I got the following pair of errors, repeating continuously every 1 second.

[18/03/2021, 14:11:44] [homebridge-gree-heatercooler-v2] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: number 30.24 exceeded maximum of 30. See https://git.io/JtMGR for more info.
[18/03/2021, 14:11:44] [homebridge-gree-heatercooler-v2] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 30.24 exceeded maximum of 30. See https://git.io/JtMGR for more info.

Everywhere I look, 86 degrees F is 30 C, but maybe the true mathematical result would actually be 30.24? So when HomeKit converts the Fahrenheit temperature to Celsius for the plugin, it is a little too accurate and it causes the over-value error.

For now, I just switched to 85 degrees and stopped the plugin from flooding my logs.

**Comment by Elethom** [comment]
Thanks for your feedback. Hopefully version 0.4.1 can solve the issue you brought up. : )

**Comment by keness521** [comment]
I updated, but I get the following error, all in solid red, and it takes Homebridge down, and restarts in a loop.

I copies some out of the logs, but it is flying by so fast hopefully you have what you need from this?

What appears to be the main error:

[19/03/2021, 12:53:08] ReferenceError: min is not defined

Some of the copy-and-paste logs:

[19/03/2021, 12:52:35] ReferenceError: min is not defined
    at GreeHeaterCooler.get targetTemperature [as targetTemperature] (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/accessory.js:249:5)
    at Device.updateCallback (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/accessory.js:85:105)
    at Device._handleResponse (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/device.js:160:14)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/device.js:21:14)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:919:8)
[19/03/2021, 12:52:36] ReferenceError: min is not defined
    at GreeHeaterCooler.get targetTemperature [as targetTemperature] (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/accessory.js:249:5)
    at Device.updateCallback (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/accessory.js:85:105)
    at Device._handleResponse (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/device.js:160:14)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/device.js:21:14)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:919:8)
[19/03/2021, 12:52:37] ReferenceError: min is not defined
    at GreeHeaterCooler.get targetTemperature [as targetTemperature] (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/accessory.js:249:5)
    at Device.updateCallback (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/accessory.js:85:105)
    at Device._handleResponse (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/device.js:160:14)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/device.js:21:14)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:919:8)
[19/03/2021, 12:52:38] ReferenceError: min is not defined
    at GreeHeaterCooler.get targetTemperature [as targetTemperature] (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/accessory.js:249:5)
    at Device.updateCallback (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/accessory.js:85:105)
    at Device._handleResponse (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/device.js:160:14)
    at Socket.<anonymous> (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/device.js:21:14)
    at Socket.emit (events.js:315:20)
    at UDP.onMessage (dgram.js:919:8)
[19/03/2021, 12:52:38] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[19/03/2021, 12:52:43] [HB Supervisor] Restarting Homebridge...

**Comment by keness521** [comment]
I reverted to 0.4.0 and it boots without crashing Homebridge, but it does give new error that weren't there before originally upgrading to 0.4.1. Also, the AC doesn't show up in HomeKit, so it isn't actually publishing the AC.

Not sure if the rollback to 0.4.0 left some residual "junk" behind, but it was working perfectly before the upgrade. Config is unchanged, and is below:

-----

{
    "accessory": "GreeHeaterCooler",
    "name": "AC 1",
    "address": "192.168.1.171",
    "mac": "f4911ef84130",
    "minimumTargetTemperature": 16,
    "maximumTargetTemperature": 30,
    "fakeSensor": false,
    "sensorOffset": 40,
    "updateInterval": 1000,
    "retryInterval": 5000
}

-----

[19/03/2021, 13:00:36] [homebridge-gree-heatercooler-v2] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[19/03/2021, 13:00:36] [homebridge-gree-heatercooler-v2] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[19/03/2021, 13:00:36] [homebridge-gree-heatercooler-v2] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: number 10 exceeded minimum of 16. See https://git.io/JtMGR for more info.
[19/03/2021, 13:00:36] [homebridge-gree-heatercooler-v2] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[19/03/2021, 13:00:36] [homebridge-gree-heatercooler-v2] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 0 exceeded minimum of 16. See https://git.io/JtMGR for more info.

**Comment by Elethom** [comment]
I'm terribly sorry for the issue. Should be fixed in 0.4.2.

**Comment by keness521** [comment]
That worked! Thanks! It doesn't crash Homebridge anymore.

I do still get the following errors when it starts, not sure perhaps the AC unit isn't responding quickly enough (NaN values) or something like that.

After a minute or two, it does show the accurate information on the Home app tile, temperature, mode, etc. And changes made transfer to the unit fine. Seems to just be a "when it first starts up" issue.

-----

[19/03/2021, 15:50:29] Loading 1 accessories...
[19/03/2021, 15:50:29] [AC 1] Initializing GreeHeaterCooler accessory...
[19/03/2021, 15:50:29] [AC 1] Config loaded: {
  "accessory": "GreeHeaterCooler",
  "name": "AC 1",
  "address": "192.168.1.171",
  "mac": "f4911ef84130",
  "minimumTargetTemperature": 16,
  "maximumTargetTemperature": 30,
  "fakeSensor": false,
  "sensorOffset": 40,
  "updateInterval": 1000,
  "retryInterval": 5000
}
Preparing Advertiser for 'Homebridge 4447 5D76' using ciao backend!
Setup Payload:
X-HM://0023YWC16UWST
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 301-75-978 │     
    └────────────┘     
                       
Starting to advertise 'Homebridge 4447 5D76' using ciao backend!
[19/03/2021, 15:50:30] Homebridge v1.3.4 (Homebridge 4447) is running on port 51225.
[19/03/2021, 15:50:30] [AC 1] Bound to device: f4911ef84130
Initializing HAP-NodeJS v0.9.4...
Initializing HAP-NodeJS v0.9.4...
[19/03/2021, 15:50:31] [homebridge-gree-heatercooler-v2] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[19/03/2021, 15:50:31] [homebridge-gree-heatercooler-v2] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[19/03/2021, 15:50:31] [homebridge-gree-heatercooler-v2] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: number 10 exceeded minimum of 16. See https://git.io/JtMGR for more info.
[19/03/2021, 15:50:31] [homebridge-gree-heatercooler-v2] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[19/03/2021, 15:50:31] [homebridge-gree-heatercooler-v2] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 0 exceeded minimum of 16. See https://git.io/JtMGR for more info.

**Comment by Elethom** [comment]
Please check the readme file. It appears that your AC unit does not have a built-in sensor and does not need the sensor offset either.

Try: 
```
"fakeSensor": true,
"sensorOffset": 0,
```

**Comment by Elethom** [comment]
And try setting the temperature to another value and then back.

**Comment by keness521** [comment]
It does have a sensor, and a short time after restarting Homebridge, maybe a minute or two, it correctly starts reporting the temperature and it does show in the HomeKit tile then as well. Without the offset, my temperatures are wild.

Even if I don't do anything, everything works perfectly, and is accurate, a couple minutes after Homebridge restarts.

But initially, it gives those errors during restart, and the Home app tile shows generic inaccurate information for a couple minutes.

I will try to restart and then right away change the temperature to another value and back to see if that "wakes it up" faster, but that wouldn't prevent the errors when HB restarts because they are immediate during startup.

**Comment by Elethom** [comment]
You can try turn on the debug option in Homebridge. It would give you raw data the AC unit send to you. That helps me understand the issue better. Thank you.

**Comment by keness521** [comment]
Will do, and will send to you ASAP. Thanks so much for all your work!

**Comment by keness521** [comment]
Hope this is helpful. I disabled my other plugins to make it less cluttered. Incidentally, I had to restart a couple times. It seems to start up perfectly fine sometimes, no errors, but not always. I would say roughly 2 out of 5 restarts generates the errors. But regardless of the errors, it always seems to successfully start its once-a-second update cycle and that seems to be working just fine. (The 1 to 2 minute delay I was seeing in HomeKit for it to "go live" probably has nothing to do with the plugin... Probably either a HomeKit thing or something with my particular setup.)

-----

[19/03/2021, 18:49:54] [HB Supervisor] Restarting Homebridge...
[19/03/2021, 18:49:54] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[19/03/2021, 18:49:54] [HB Supervisor] Started Homebridge v1.3.4 with PID: 23628
Initializing HAP-NodeJS v0.9.4...
[19/03/2021, 18:49:55] Loaded config.json with 1 accessories and 3 platforms.
[19/03/2021, 18:49:55] Loaded 0 cached accessories from cachedAccessories.
[19/03/2021, 18:49:55] ---
[19/03/2021, 18:49:56] Disabled plugin: homebridge-camera-ffmpeg@3.1.2
[19/03/2021, 18:49:56] ---
[19/03/2021, 18:49:56] Loaded plugin: homebridge-config-ui-x@4.40.0
[19/03/2021, 18:49:56] Registering platform 'homebridge-config-ui-x.config'
[19/03/2021, 18:49:56] ---
[19/03/2021, 18:49:56] Loaded plugin: homebridge-gree-heatercooler-v2@0.4.2
[19/03/2021, 18:49:56] Registering accessory 'homebridge-gree-heatercooler-v2.GreeHeaterCooler'
[19/03/2021, 18:49:56] ---
[19/03/2021, 18:49:58] Disabled plugin: homebridge-hue@0.13.3
[19/03/2021, 18:49:58] ---
[19/03/2021, 18:49:58] Loading 3 platforms...
[19/03/2021, 18:49:58] [Config] Initializing config platform...
[19/03/2021, 18:49:58] [Config] Running in Service Mode
[19/03/2021, 18:49:58] Ignoring config for the platform "Camera-ffmpeg" in your config.json as the plugin "homebridge-camera-ffmpeg" has been disabled.
[19/03/2021, 18:49:58] Ignoring config for the platform "Hue" in your config.json as the plugin "homebridge-hue" has been disabled.
[19/03/2021, 18:49:58] Loading 1 accessories...
[19/03/2021, 18:49:58] [AC 1] Initializing GreeHeaterCooler accessory...
[19/03/2021, 18:49:58] [AC 1] Config loaded: {
  "accessory": "GreeHeaterCooler",
  "name": "AC 1",
  "address": "192.168.1.171",
  "mac": "f4911ef84130",
  "minimumTargetTemperature": 16,
  "maximumTargetTemperature": 30,
  "fakeSensor": false,
  "sensorOffset": 40,
  "updateInterval": 1000,
  "retryInterval": 5000
}
[19/03/2021, 18:49:58] [AC 1] Setup socket
Preparing Advertiser for 'Homebridge 4447 5D76' using ciao backend!
Setup Payload:
X-HM://0023YWC16UWST
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 301-75-978 │     
    └────────────┘     
                       
[19/03/2021, 18:49:58] [AC 1] Bind to device: f4911ef84130
[19/03/2021, 18:49:58] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"bind","uid":0}
[19/03/2021, 18:49:58] [AC 1] Binding to device at 192.168.1.171:7000(f4911ef84130)
[19/03/2021, 18:49:58] [AC 1] Socket setup at 58128
Starting to advertise 'Homebridge 4447 5D76' using ciao backend!
[19/03/2021, 18:49:58] Homebridge v1.3.4 (Homebridge 4447) is running on port 51225.
[19/03/2021, 18:49:58] [AC 1] Bound to device: f4911ef84130
[19/03/2021, 18:49:59] [AC 1] [f4911ef84130] Get characteristic: active
[19/03/2021, 18:49:59] [AC 1] [f4911ef84130] Get characteristic: currentState
[19/03/2021, 18:49:59] [AC 1] [f4911ef84130] Get characteristic: targetState
[19/03/2021, 18:49:59] [AC 1] [f4911ef84130] Get characteristic: currentTemperature
[19/03/2021, 18:49:59] [homebridge-gree-heatercooler-v2] This plugin generated a warning from the characteristic 'Current Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[19/03/2021, 18:49:59] [homebridge-gree-heatercooler-v2] Error: 
    at CurrentTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at CurrentTemperature.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1533:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at GreeHeaterCooler.onGet (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/accessory.js:267:7)
    at CurrentTemperature.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at CurrentTemperature.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
[19/03/2021, 18:49:59] [AC 1] [f4911ef84130] Get characteristic: speed
[19/03/2021, 18:49:59] [AC 1] [f4911ef84130] Get characteristic: units
[19/03/2021, 18:49:59] [AC 1] [f4911ef84130] Get characteristic: swingMode
[19/03/2021, 18:49:59] [AC 1] [f4911ef84130] Get characteristic: targetTemperature
[19/03/2021, 18:49:59] [homebridge-gree-heatercooler-v2] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[19/03/2021, 18:49:59] [homebridge-gree-heatercooler-v2] Error: 
    at CoolingThresholdTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at CoolingThresholdTemperature.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1533:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at GreeHeaterCooler.onGet (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/accessory.js:267:7)
    at CoolingThresholdTemperature.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at CoolingThresholdTemperature.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
[19/03/2021, 18:49:59] [homebridge-gree-heatercooler-v2] This plugin generated a warning from the characteristic 'Cooling Threshold Temperature': characteristic was supplied illegal value: number 10 exceeded minimum of 16. See https://git.io/JtMGR for more info.
[19/03/2021, 18:49:59] [homebridge-gree-heatercooler-v2] Error: 
    at CoolingThresholdTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at CoolingThresholdTemperature.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1946:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1533:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at GreeHeaterCooler.onGet (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/accessory.js:267:7)
    at CoolingThresholdTemperature.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at CoolingThresholdTemperature.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
[19/03/2021, 18:49:59] [AC 1] [f4911ef84130] Get characteristic: targetTemperature
[19/03/2021, 18:49:59] [homebridge-gree-heatercooler-v2] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic value expected valid finite number and received "NaN" (number). See https://git.io/JtMGR for more info.
[19/03/2021, 18:49:59] [homebridge-gree-heatercooler-v2] Error: 
    at HeatingThresholdTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at HeatingThresholdTemperature.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1931:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1533:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at GreeHeaterCooler.onGet (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/accessory.js:267:7)
    at HeatingThresholdTemperature.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at HeatingThresholdTemperature.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
[19/03/2021, 18:49:59] [homebridge-gree-heatercooler-v2] This plugin generated a warning from the characteristic 'Heating Threshold Temperature': characteristic was supplied illegal value: number 0 exceeded minimum of 16. See https://git.io/JtMGR for more info.
[19/03/2021, 18:49:59] [homebridge-gree-heatercooler-v2] Error: 
    at HeatingThresholdTemperature.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2038:105)
    at HeatingThresholdTemperature.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1946:16)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1533:24
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/util/once.ts:9:18
    at GreeHeaterCooler.onGet (/usr/local/lib/node_modules/homebridge-gree-heatercooler-v2/dist/accessory.js:267:7)
    at HeatingThresholdTemperature.emit (events.js:315:20)
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1508:14
    at new Promise (<anonymous>)
    at HeatingThresholdTemperature.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1506:12)
    at step (/usr/local/lib/node_modules/homebridge/node_modules/tslib/tslib.js:143:27)
[19/03/2021, 18:49:59] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:49:59] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:49:59] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}
[19/03/2021, 18:50:00] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:50:00] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:50:00] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}
[19/03/2021, 18:50:01] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:50:01] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:50:01] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}
[19/03/2021, 18:50:02] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:50:02] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:50:02] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}
[19/03/2021, 18:50:03] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:50:03] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:50:03] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}

**Comment by keness521** [comment]
Here is a restart cycle where it DIDN'T generate the errors. This boot was immediate before the one in my previous message. When I saw it didn't generate the errors, I simply pressed the restart Homebridge button again to get the one in my previous message, which did have the errors. I made no other changes.

-----

[19/03/2021, 18:49:16] [HB Supervisor] Restarting Homebridge...
[19/03/2021, 18:49:16] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[19/03/2021, 18:49:16] [HB Supervisor] Started Homebridge v1.3.4 with PID: 23182
Initializing HAP-NodeJS v0.9.4...
[19/03/2021, 18:49:17] Loaded config.json with 1 accessories and 3 platforms.
[19/03/2021, 18:49:17] Loaded 0 cached accessories from cachedAccessories.
[19/03/2021, 18:49:17] ---
[19/03/2021, 18:49:18] Disabled plugin: homebridge-camera-ffmpeg@3.1.2
[19/03/2021, 18:49:18] ---
[19/03/2021, 18:49:18] Loaded plugin: homebridge-config-ui-x@4.40.0
[19/03/2021, 18:49:18] Registering platform 'homebridge-config-ui-x.config'
[19/03/2021, 18:49:18] ---
[19/03/2021, 18:49:18] Loaded plugin: homebridge-gree-heatercooler-v2@0.4.2
[19/03/2021, 18:49:18] Registering accessory 'homebridge-gree-heatercooler-v2.GreeHeaterCooler'
[19/03/2021, 18:49:18] ---
[19/03/2021, 18:49:20] Disabled plugin: homebridge-hue@0.13.3
[19/03/2021, 18:49:20] ---
[19/03/2021, 18:49:20] Loading 3 platforms...
[19/03/2021, 18:49:20] [Config] Initializing config platform...
[19/03/2021, 18:49:20] [Config] Running in Service Mode
[19/03/2021, 18:49:20] Ignoring config for the platform "Camera-ffmpeg" in your config.json as the plugin "homebridge-camera-ffmpeg" has been disabled.
[19/03/2021, 18:49:20] Ignoring config for the platform "Hue" in your config.json as the plugin "homebridge-hue" has been disabled.
[19/03/2021, 18:49:20] Loading 1 accessories...
[19/03/2021, 18:49:20] [AC 1] Initializing GreeHeaterCooler accessory...
[19/03/2021, 18:49:20] [AC 1] Config loaded: {
  "accessory": "GreeHeaterCooler",
  "name": "AC 1",
  "address": "192.168.1.171",
  "mac": "f4911ef84130",
  "minimumTargetTemperature": 16,
  "maximumTargetTemperature": 30,
  "fakeSensor": false,
  "sensorOffset": 40,
  "updateInterval": 1000,
  "retryInterval": 5000
}
[19/03/2021, 18:49:20] [AC 1] Setup socket
Preparing Advertiser for 'Homebridge 4447 5D76' using ciao backend!
Setup Payload:
X-HM://0023YWC16UWST
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 301-75-978 │     
    └────────────┘     
                       
[19/03/2021, 18:49:20] [AC 1] Bind to device: f4911ef84130
[19/03/2021, 18:49:20] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"bind","uid":0}
[19/03/2021, 18:49:20] [AC 1] Binding to device at 192.168.1.171:7000(f4911ef84130)
[19/03/2021, 18:49:20] [AC 1] Socket setup at 54984
Starting to advertise 'Homebridge 4447 5D76' using ciao backend!
[19/03/2021, 18:49:20] Homebridge v1.3.4 (Homebridge 4447) is running on port 51225.
[19/03/2021, 18:49:20] [AC 1] Bound to device: f4911ef84130
[19/03/2021, 18:49:21] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:49:21] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:49:21] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}
[19/03/2021, 18:49:21] [AC 1] [f4911ef84130] Get characteristic: active
[19/03/2021, 18:49:21] [AC 1] [f4911ef84130] Get characteristic: currentState
[19/03/2021, 18:49:21] [AC 1] [f4911ef84130] Get characteristic: targetState
[19/03/2021, 18:49:21] [AC 1] [f4911ef84130] Get characteristic: currentTemperature
[19/03/2021, 18:49:21] [AC 1] [f4911ef84130] Get characteristic: speed
[19/03/2021, 18:49:21] [AC 1] [f4911ef84130] Get characteristic: units
[19/03/2021, 18:49:21] [AC 1] [f4911ef84130] Get characteristic: swingMode
[19/03/2021, 18:49:21] [AC 1] [f4911ef84130] Get characteristic: targetTemperature
[19/03/2021, 18:49:21] [AC 1] [f4911ef84130] Get characteristic: targetTemperature
[19/03/2021, 18:49:22] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:49:22] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:49:22] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}
[19/03/2021, 18:49:23] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:49:23] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:49:23] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}
[19/03/2021, 18:49:24] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:49:24] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:49:24] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}
[19/03/2021, 18:49:25] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:49:25] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:49:25] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}
[19/03/2021, 18:49:26] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:49:26] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:49:26] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}
[19/03/2021, 18:49:27] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:49:27] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:49:27] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}
[19/03/2021, 18:49:28] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:49:28] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:49:28] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}
[19/03/2021, 18:49:29] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:49:29] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:49:29] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}
[19/03/2021, 18:49:30] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:49:30] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:49:30] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}
[19/03/2021, 18:49:31] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:49:31] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:49:31] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}
[19/03/2021, 18:49:32] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:49:32] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:49:32] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}
[19/03/2021, 18:49:33] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:49:33] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:49:33] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}
[19/03/2021, 18:49:34] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:49:34] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:49:34] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}
[19/03/2021, 18:49:35] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:49:35] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:49:35] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}
[19/03/2021, 18:49:36] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:49:36] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:49:36] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}
[19/03/2021, 18:49:37] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:49:37] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:49:37] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}
[19/03/2021, 18:49:38] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:49:38] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:49:38] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}
[19/03/2021, 18:49:39] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:49:39] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:49:39] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}
[19/03/2021, 18:49:40] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:49:40] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:49:40] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}
[19/03/2021, 18:49:41] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:49:41] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:49:41] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}
[19/03/2021, 18:49:42] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:49:42] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:49:42] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}
[19/03/2021, 18:49:43] [AC 1] [f4911ef84130] Update status for keys: Pow,Mod,SetTem,TemSen,TemUn,TemRec,WdSpd,SwUpDn
[19/03/2021, 18:49:43] [AC 1] [f4911ef84130] Send request: {"mac":"f4911ef84130","t":"status","cols":["Pow","Mod","SetTem","TemSen","TemUn","TemRec","WdSpd","SwUpDn"]}
[19/03/2021, 18:49:43] [AC 1] [f4911ef84130] Status updated: {"Pow":1,"Mod":4,"SetTem":30,"TemSen":63,"TemUn":1,"TemRec":1,"WdSpd":0,"SwUpDn":0}
[19/03/2021, 18:49:44] [Homebridge UI] Homebridge restart request received
[19/03/2021, 18:49:44] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[19/03/2021, 18:49:44] [Homebridge UI] Sending SIGTERM to Homebridge
[19/03/2021, 18:49:44] Got SIGTERM, shutting down Homebridge...

**Comment by Elethom** [comment]
That's probably because your device tries to fetch status before Homebridge makes contact with the AC unit. I added better empty value handling in 0.4.3. Feel free to try it.

**Comment by keness521** [comment]
Perfecto. Restarted a whole bunch of times, flawless every time.
